# Generated by Django 5.1.2 on 2024-11-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
