# Generated by Django 5.1.2 on 2024-11-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="product_name",
        ),
    ]
