# Generated by Django 5.1.2 on 2024-11-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_rename_name_product_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="vendor_id",
        ),
    ]
