# Generated by Django 5.1.2 on 2024-11-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("color", "color"), ("size", "size")], max_length=100
            ),
        ),
    ]
