# Generated by Django 5.1.2 on 2024-11-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="password",
            field=models.CharField(default=0, max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
