# Generated by Django 5.1.2 on 2024-11-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_last_login_account_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="username",
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
