# Generated by Django 5.1.2 on 2024-11-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cartitem"),
        ("product", "0004_alter_variation_variation_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variation",
            field=models.ManyToManyField(blank=True, to="product.variation"),
        ),
    ]
